apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-helm-config
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-helm-config
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: apps/guestbook-helm-options
    repoURL: "https://github.com/vigilentMOE/argolab.git"
    targetRevision: main
    helm: 
      releaseName: my-custom-release-name
  syncPolicy:
    syncOptions:
      - CreateNamespace=true